#!/usr/bin/env bash
# This script configures a brand new Ubuntu machine to contain custom header

sudo apt-get update -y
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.6
sudo apt-get -y install haproxy
# sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
printf %s "
frontend main
    bind *:80
    option forwardfor  
    default_backend app-main

backend app-main
    balance roundrobin
    server 247963-web-01	18.234.107.37 check
    server 247963-web-02	52.91.151.209 check
    " >> /etc/haproxy/haproxy.cfg
sudo service haproxy start