#!/usr/bin/env bash
# a bash script that creates the file /var/run/myscript.pid containing its PID
# displays to infinity and beyond indefinitely
# displays i hate the kill command when receiving a SIGTERM signal
# displays y u know love me?! when receiving a SIGINT signal
# deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

terminator() {
rm /var/run/myscript.pid
exit
}

echo "$$" > /var/run/myscript.pid

while true
do
echo "To infiniy and beyond"
sleep 2
trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command" && terminator' SIGTERM
trap 'terminator' SIGQUITgit
done