#!/usr/bin/env bash
# This script displays the content of /etc/passwd with username, user ID, and home directory path

while IFS=':' read -r username _ userid _ _ _ homedir _
do
    echo "$username:$userid:$homedir"
done < /etc/passwd