#!/usr/bin/env bash

while IFS=':' read -r username _ userid groupid _ homedir shell
do
    read -r _ _ _ _ info <<< "$(grep "^$username:" /etc/passwd)"
    read -r _ _ password _ <<< "$info"

    echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell. $userid's place is protected by the passcode $password, more info about the user here: $info"
done < /etc/passwd